### ISSUE TITLE
BERT version

### ISSUE THREAD

**Issue by mtt1998** [tdopierre/ProtAugment#1]
Hi,
      Thank you for sharing the code! I'm wondering which version encoder did you use in the experiments. "BERT-base-uncased" or "BERT-base-cased" model?

**Comment by tdopierre** [comment]
Hi @mtt1998,
Sorry for answering late.
In our experiments, we fine-tune language models on each dataset, using the masked language modeling task. The starting point of this fine-tuning is the `bert-base-cased` model. Such fine-tuned language models are then used in the prototypical network.
Does that answer your question?

**Comment by mtt1998** [comment]
Yes ! Thank you !
